### ISSUE TITLE
Unbalanced designs

### ISSUE THREAD

**Issue by SondreNilsen** [lebebr01/simglm#102]
First of all, thank you for a great package. 

I am trying to simulate data for a three-level design with unbalanced data. 
Simulating data with a three-level (balanced) structure is easy, thanks to you! However, I have not been able to tweak my code to simulate unbalanced data while retaining a given pre-determined total sample size at each level. 

Is this possible? 

Best, 
Sondre

**Comment by lebebr01** [comment]
Thanks for your comment and interest in the package. Are you able to share any code to help me understand more fully what you currently have and what should be modified?
