### ISSUE TITLE
ambiguous error 

### ISSUE THREAD

**Issue by K3JT** [lebebr01/simglm#12]
modifying the code from the vignette, I get an ambiguous error.  

```{r one}
fixed <- ~ 1 + day.o + shift.o + treat.o 
fixed_param <- c(2, 4, 1, 3.5)
cov_param <- NULL
fact_vars <- list(numlevels = c(7, 3, 3), var_type = c('single', 'single', "single"))
n <- 150
error_var <- 3
with_err_gen = 'rnorm'
temp_single <-  sim_reg(fixed = fixed,  fixed_param = fixed_param,
  cov_param = cov_param, n = n, error_var = error_var,
  with_err_gen = with_err_gen,  data_str = "single")

dim(temp_single)
head(temp_single)
```

Error in if (var_type == "single" | var_type == "lvl2") { : 
  argument is of length zero

My goal is to estimate power / sample size for a longitudinal study involving  a categorical fixed effects for 3 treatment levels.  The data consist of categorical  fixed effects for  daily measurements on subjects at three times per day for two weeks.  (then repeated at 4 time periods).  random effect intercepts for subjects and a random effect to account for correlation of measurements within a time period.  I would like to start with 150 subjects per treatment to estimate power and possible smaller numbers of subjects.    I try this code but get the same error message.

```r

fixed <- ~ 1 + time + day.o + shift.o + treat.o + day.o:treat.o
random <- ~ 1 + time
fixed_param <- c(0.5, 0.8, 1, 0.2, 0.1, 0)
random_param <- list(random_var = c(7, 4), rand_gen = "rnorm")
cov_param <- list(mean = c(0, 0), sd = c(1, 1), var_type = c("lvl1", "lvl2"))
fact_vars <- list(numlevels = c(7, 3, 3), var_type = c('single', 'single', "single"))
n <- 150
p <- 4
error_var <- 3
data_str <- "long"
with_err_gen = 'rnorm'

temp_long <- sim_reg(fixed = fixed, random = random, 
                     fixed_param = fixed_param, 
                     random_param = random_param, cov_param = cov_param, 
                     k = NULL, n = n, p = p,
                     error_var = error_var, with_err_gen = "rnorm",
                     data_str = data_str, unbal = FALSE)
```

I would be grateful for any suggestions you can offer.

**Comment by lebebr01** [comment]
I apologize for the delayed response. I've been adjusting a few aspects of the package prior to release and have not written tests yet for simulation of factor variables. 

I will prioritize fixing this error.

**Comment by K3JT** [comment]
Brandon,

Thanks for your response.  I think your package would help with a problem I am working on , to estimate sample size / power for a longitudinal study with multiple factor variables and 5 time periods (possibly AR1 correlation structure).  I have (so far) used “simr” but your “simglm” offers more options and  flexibility.   When you have time, I would welcome the opportunity to discuss this.

Terry


James T. Wassell, Ph.D.
National Institute for Occupational Safety and Health
Division of Safety Research.
Analysis and Field Evaluations Branch.
Morgantown, WV  26501
304.285.5946
JTW2@cdc.gov<mailto:JTW2@cdc.gov>
