### ISSUE TITLE
Allow factor variables in the random component?

### ISSUE THREAD

**Issue by jknowles** [lebebr01/simglm#31]
Is it possible to specify a factor in the random component? 

I want to generate data where some of the variables are factors which are consistent within cluster. 
```
fixed <- ~1 + time 
random <- ~1 + time + gifted.f + iep.f + frpl.f + ell.f 
random3 <- ~ 1
fixed_param <- c(100, 25, 10)
fact_vars <- list(numlevels = c(2, 2, 2, 2),  var_type = c(rep('lvl2', 4)))
random_param <- list(random_var = c(50, 90, 10, 10, 10, 10), rand_gen = "rnorm") 
random_param3 <- list(random_var = c(200), rand_gen = 'rnorm') 
unbalCont <- c(2, 16)
unbalCont3 <- c(100, 800)
k <- 15 
n <- 200
p <- 400
error_var <- 10
with_err_gen <- 'rnorm'
lvl1_err_params <- list(mean = 20, sd = 10)
data_str <- "long"
cov_param <- NULL
temp_three <- sim_reg(fixed = fixed, random = random, random3 = random3,
                      fixed_param = fixed_param, random_param = random_param,
                      random_param3 = random_param3, cov_param = cov_param,
                      fact_vars = fact_vars, k = k,n = n, p = p,
                      lvl1_err_params = lvl1_err_params,
                      error_var= error_var, with_err_gen = with_err_gen,
                      cor_vars = cor_vars, data_str = data_str, unbal = TRUE,
                      unbalCont = unbalCont, unbalCont3 = unbalCont3)
```

I don't understand what I'm doing wrong in specifying this. Is it just that putting factors in the 2nd or 3rd level is not possible currently?

**Comment by lebebr01** [comment]
I have not currently generalized the code to allow factors in the random portion. This should be a relatively easy extension from the fixed effects portion of the models to generate the random effect design matrix.

**Comment by lebebr01** [comment]
Upon thinking about this in more detail, this model does not make sense to me. The random effects should be continuous not factors. Therefore, adding factors in the random component is not possible or meaningful.

If you'd like to generate data in which there are subject specific deviations for ELL or gifted students, why not treat these as fixed which is more common? The grouping is not random, the students are random.
