### ISSUE TITLE
PR help?

### ISSUE THREAD

**Issue by jknowles** [lebebr01/simglm#32]
Hi @lebebr01 

This is a really great package. I have a lot of need for a tool that does exactly these tasks in a production environment. 

Would you have any interest in a pull-request that:

- Cleans up some of the documentation adding more details about how to specify arguments (related to #30 )
- Modifies all code to pass CRAN checks

With an end goal of listing the package on CRAN? I have two packages published on CRAN so would be happy to assist with this. Your package is 95% of the way there, and it would be great to make available for others needing to simulate complex hierarchical processes.

**Comment by lebebr01** [comment]
Thanks for the useful comments @jknowles. I'm open to pull requests, particularly related to areas in the documentation that needs additional clarification. This is always a struggle initially in terms of what makes sense to me versus what helps users engage with the functions. Feedback is appreciated with this.

I'd also be open to features that are currently not implemented that would be a useful addition. If they are easy to implement, these could be included prior to CRAN submission. More difficult additions (e.g. simulating poisson processes) would likely be added to a road map for future releases.

My short term goal is to spend more time on this over the next 4 to 6 weeks and push to CRAN. Regarding CRAN checks, I believe the package currently passes these and changes to current code would just need to continue passing the CRAN checks.

**Comment by jknowles** [comment]
Awesome. If it helps I can tackle the documentation stuff in a PR quickly based on your helpful replies to other issues. 

If there are other things you would like assistance with, just let me know. This package is really helpful and I'd love to contribute if it will help you out.
