### ISSUE TITLE
vignette example run error

### ISSUE THREAD

**Issue by JanSouren** [lebebr01/simglm#38]
> knit_print.data.frame = function(x, ...) {
+   res = paste(c('', '', kable(x, output = FALSE)), collapse = '\n')
+   asis_output(res)
+ }
> fixed <- ~ 1 + act + diff + numCourse + act:numCourse
> fixed_param <- c(2, 4, 1, 3.5, 2)
> cov_param <- list(mean = c(0, 0, 0), sd = c(4, 3, 3), var_type = c("single", "single", "single"))
> n <- 150
> error_var <- 3
> with_err_gen = 'rnorm'
> temp_single <- sim_reg(fixed = fixed, fixed_param = fixed_param, cov_param = cov_param,
+                        n = n, error_var = error_var, with_err_gen = with_err_gen, 
+                        data_str = "single")
Error in `colnames<-`(`*tmp*`, value = c("Fbeta", "err", "sim_data")) : 
  length of 'dimnames' [2] not equal to array extent
In addition: Warning message:
In cbind(Fbeta, err, sim_data) :
  number of rows of result is not a multiple of vector length (arg 2)

**Comment by lebebr01** [comment]
Did you specifically build vignettes when installing the package from github? I do not compile the vignettes when pushing to github.

```
install_github("lebebr01/simglm", build_vignettes = TRUE)
```

**Comment by lebebr01** [comment]
I just verified, if this is indeed the first example from the intro vignette, it does run on my end (and passes when running checks on my machine and on travis CI). I would ensure you install the latest vignettes by building them using the code from the previous comment.

**Comment by JanSouren** [comment]
Hello Brandon,

Thanks for your reaction.
Sorry for the late reply. I installed the package as described in the code below and yet obtained the error mentioned.

Best regards,
Jan

**Comment by lebebr01** [comment]
I am again unable to verify this error on two separate computers with new installation directly from github and had a colleague install and run the vignette. No issues on any of those. There must be some issue specific to your installation in which the package is not updated correctly. 

I would recommend removing the package and installing again or waiting for the CRAN release hopefully out by the end of the month.

**Comment by JanSouren** [comment]
Thanks again for all your work,

I for now just downloaded the file directly from github.

Best regards
Jan
