### ISSUE TITLE
question: how to include offset in poisson reg

### ISSUE THREAD

**Issue by statsccpr** [lebebr01/simglm#56]
Hi i was checking out your package and it seems great.

A question I had is, how do you include an offset in a poisson regression simulation.

From my tests, i'm guessing it currently can not be done?

I tried the below code, adapted from the manual.

It looks like the API design does not have a good place to specify 'offset' data conditions

The non-offset poisson regression has an intercept, requires the user to specify the intercepts parameter, and by default the intercepts data condition is not needed for the cov_par.

However, the offset poisson regression removes the intercept, does not need the parameter, and 'ideally' needs to have the user specify the data condition of the offset. The code below tries that scenario but gets an error

``` Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent
```

The main difference I see is that with an offset, the offset variables data distribution needs to be specified but it should not require a parameter

This is a different setting than the non-offset poisson regression in the manual;
1 additional data dist, but 1 less parameter 

```
# https://brandonlebeau.org/2017/07/24/simglm-jsm/

# install.packages('simglm')
library(simglm)

########################
# formula
########################

# manual example
fixed <- ~1 + act + diff

# offset variant
fixed <- ~ offset(foo_offset) - 1 + act + diff

########################
# fixed_param
########################
# no param for offset, 
# manual makes it seem only "true" covariates
# intercept, act, diff
# fixed_param <- c(-0.5, 0.5, 0.3)


# there should be no parameter for the offset
# act, diff
fixed_param <- c(0.5, 0.3)


########################
# cov_param
########################
# looks like intercept is ignored below
# looks like offset should not be included here, 
# but then, where to include offset?


# cov_param <- list(dist_fun = c('rnorm', 'rnorm'),
#                   var_type = c("single", "single"),
#                   opts = list(list(mean = 0, sd = 4),
#                               list(mean = 0, sd = 3)))


cov_param <- list(dist_fun = c('rnorm','rnorm', 'rnorm'),
                  var_type = c('single',"single", "single"),
                  opts = list(list(mean = 0, sd = 4), # offset
                              list(mean = 0, sd = 4), # act
                              list(mean = 0, sd = 3)) # diff
)

n <- 150

temp_single <- sim_glm(fixed = fixed, fixed_param = fixed_param, 
                       cov_param = cov_param, 
                       n = n, data_str = "single", outcome_type = 'poisson')

print(temp_single, n = 5)

# Error in dimnames(x) <- dn : 
#   length of 'dimnames' [2] not equal to array extent
# probably because 'settings' for foo_offset' is not correctly specified
# 1 additional data dist, but 1 less parameter 

# intercept did not have to be specified in 'cov_param'



```

**Comment by lebebr01** [comment]
Thanks for the comment and interest in the package. 

Yes, you are correct, currently this is not supported/flexible enough to handle this type of term. Partially this is due to me never fitting a model like this. Would you have a reference to a paper that gives an example of this model? Otherwise if you would want to take a stab at adding this and send a pull request, that would be helpful as well.
