### ISSUE TITLE
Examples cause errors on mac

### ISSUE THREAD

**Issue by p1981thompson** [lebebr01/simglm#59]
We (@oscci and I) have tried running the following examples from the vignettes and your blog which generate the following error when run on a mac (no issue on windows PC):

 **"Error in sample.int(length(x), size, replace, prob) : cannot take a sample larger than the population when 'replace = FALSE'"**

Examples causing problems:

#example with sim_reg
fixed <- ~ 1 + act_o + income + grad_degree_f
fixed_param <- c(3.2, 0.4, 0.02, 0.6)
random <- ~ 1 
random_param <- list(random_var = 10, rand_gen = 'rnorm')
cov_param <- list(dist_fun = 'rnorm',
                  var_type = 'level1')
n <- 50
p <- 5
error_var <- 5
with_err_gen <- 'rnorm'
data_str <- 'cross'
fact_vars <- list(numlevels = c(36, 2), 
                  var_type = c('level1', 'level1'))

sim_reg(fixed = fixed, fixed_param = fixed_param, random = random,
        random_param = random_param, cov_param = cov_param, k = NULL, n = n, p = p,
        error_var = error_var, with_err_gen = with_err_gen, 
        data_str = data_str, fact_vars = fact_vars)

#--------------------------------------------------------------------#
another example from https://brandonlebeau.org/2017/07/24/simglm-jsm/:  this one does NOT work

fixed <- ~ 1 + act_o + income + grad_degree_f
fixed_param <- c(0.5, 0.4, 0.02, 0.6)
random <- ~ 1 
random_param <- list(random_var = 10, rand_gen = 'rnorm')
cov_param <- list(dist_fun = 'rnorm',
                  var_type = 'level1')
n <- 50
p <- 5
data_str <- 'cross'
fact_vars <- list(numlevels = c(36, 2), 
                  var_type = c('level1', 'level1'))

sim_glm(fixed = fixed, fixed_param = fixed_param, random = random,
        random_param = random_param, cov_param = cov_param, k = NULL, n = n, p = p,
        data_str = data_str, fact_vars = fact_vars, outcome_type = 'logistic')
#--------------------------------------------------------------------#
We also have problems with our own our poisson regression

fixed <- ~ 1 + sum_pLi + Group.o + sum_pLi:Group.o 

#one sided formula that gives the names of the variables to be included in the simulated data. The intercept is directly shown in the formulation here, but can also be omitted

#To add a factor, categorical, or ordinal variable, just append one of the following to the end of the variable name in the fixed object: “.f”, “.c”, “.o”, “_f“,”_c“, or”_o“. These indicate the variable is a discrete variable of some sort. By default, all variables with a”.f" or “.c” will be treated as factors and expanded using dummy coding. If “.o” is used in the variable names, the variable will be discrete but treated as continuous in the simulation (i.e. only a single fixed effect variable).

fixed_param <- c(-1.5, 0.3, 0.1, 0.1) 

#regression weights for the fixed effects, this must be the same length as fixed (or one larger if the 1 is not explicitly stated in the fixed object).

cov_param <- list(dist_fun = c('rnorm'),
                  var_type = c("single"),
                  opts = list(list(mean = 0, sd = 2)))

#mean, standard deviation, and type of variable from the fixed object (must by “single” for single level regression). The cov_param object must contain all variables except the intercept and any interactions.

fact_vars <- list(numlevels = 2,var_type='single')# fact_vars is a list that contains numlevels and var_type.
#cor_vars<-0.3
#--------------------------------------------------------------------#
myn <- 130 #sample size
error_var <- 5 #error variance
with_err_gen = 'rnorm' #distribution of residuals

pow_param <- c('(Intercept)', 'sum_pLi', 'Group.o','sum_pLi:Group.o')
alpha <- .01
pow_dist <- "z"
pow_tail <- 2
replicates <- 100

power_out <- sim_pow_glm(fixed = fixed, fixed_param = fixed_param, 
                         cov_param = cov_param, 
                         n = myn, data_str = "single", 
                         outcome_type = 'poisson', fact_vars = fact_vars,
                         pow_param = pow_param, alpha = alpha,
                         pow_dist = pow_dist, pow_tail = pow_tail, 
                         replicates = replicates, raw_power = FALSE)
#---------------------------------------------------------------------------#

**Comment by oscci** [comment]
Just to add to Paul's examples, the error with a mac is seen only with some of the vignette scripts. I have examples here https://github.com/oscci/CNV_hayley/blob/master/simglmvignette.R
The ones at the start of the file all ran fine on my mac: I've inserted a comment after those to show the set of scripts that failed (equiv to those in Paul's) message.
To load the package, we used the command 
install_github("lebebr01/simglm", build_vignettes = TRUE)

**Comment by oscci** [comment]
P.S. Hadley Wickham has just announced a new package 'conflicted', which will flag up functions with conflicts. I had wondered if this might be responsible for the error, but no conflicts were picked up.

**Comment by lebebr01** [comment]
Thanks for these reports of errors. Two issues happening here:

1. The package had a bug in the DESCRIPTION file which caused me to push this release a bit early as it was going to be removed from CRAN. 
2. The API of the package is shifting slightly toward a tidy simulation framework and code that is more maintainable, see the two newer vignettes for examples of this framework in action (https://github.com/lebebr01/simglm/blob/master/vignettes/tidy_simulation.Rmd] and https://github.com/lebebr01/simglm/blob/master/vignettes/simulation_arguments.Rmd). With that said, I'm trying to also keep backwards compatibility with legacy code, therefore will hopefully have a fix later this week for this. 

It is recommended to shift the legacy code to the new framework, I can post an example of your simulation code in the new framework soon. In addition, I plan to advertise the new tidy simulation framework later this week. I can share those examples here as well.

**Comment by lebebr01** [comment]
@p1981thompson and @oscci. I have officially confirmed the error message you reported. I have two solutions below that work on the current developmental version of simglm on GitHub for your data example.

This first solution uses the old simglm style code. The main addition is adding `opts = list(list(replace = TRUE))` to the `fact_vars` argument:
  
  ```
fixed <- ~ 1 + sum_pLi + Group.o + sum_pLi:Group.o
fixed_param <- c(-1.5, 0.3, 0.1, 0.1)
cov_param <- list(dist_fun = c('rnorm'),
                  var_type = c("single"),
                  opts = list(list(mean = 0, sd = 2)))
fact_vars <- list(numlevels = 2,
                  var_type='single', 
                  opts = list(list(replace = TRUE)))
myn <- 130 #sample size
error_var <- 5 #error variance
with_err_gen = 'rnorm' #distribution of residuals

pow_param <- c('(Intercept)', 'sum_pLi', 'Group.o','sum_pLi:Group.o')
alpha <- .01
pow_dist <- "z"
pow_tail <- 2
replicates <- 100

power_out <- sim_pow_glm(fixed = fixed, fixed_param = fixed_param,
                         cov_param = cov_param,
                         n = myn, data_str = "single",
                         outcome_type = 'poisson', fact_vars = fact_vars,
                         pow_param = pow_param, alpha = alpha,
                         pow_dist = pow_dist, pow_tail = pow_tail,
                         replicates = replicates, raw_power = FALSE)
```

Below is also the new simglm style syntax that I am going to suggest users migrate to (note, you will need the latest development version from GitHub for this code to run properly). This code will be expanded and maintained over time. In addition, I'm planning a maintenance/documentation release within the next month followed by a series of blog posts to highlight the newer syntax in more detail.

```
# Tidy Analysis
library(tidyverse)

sim_arguments <- list(
  formula = counts ~ 1 + sum_pLi + Group + sum_pLi:Group,
  fixed = list(
    sum_pLi = list(var_type = 'continuous', mean = 0, sd = 2),
    Group = list(var_type = 'factor', levels = c('A', 'B'))
  ),
  sample_size = 130,
  error = list(variance = 5),
  reg_weights = c(-1.5, 0.3, 0.1, 0.1),
  power = list(
    dist = 'qnorm',
    alpha = .01
  ),
  replications = 100
)

# Explore data generation makes sense
simulate_fixed(data = NULL, sim_arguments) %>%
  generate_response(sim_arguments)

# Explore a single replication - model parameters
simulate_fixed(data = NULL, sim_arguments) %>%
  generate_response(sim_arguments) %>% 
  model_fit(sim_arguments) %>%
  extract_coefficients()

# replicate the simulation for power analysis
replicate_simulation(sim_arguments, 
                     simulate_fixed(data = NULL, sim_arguments) %>%
                       generate_response(sim_arguments) %>% 
                       model_fit(sim_arguments) %>%
                       extract_coefficients()) %>%
  compute_statistics(sim_arguments)
```

One note, the two representations give different results. The reason for this is that the newer syntax uses a slightly different parameterization for the factor variable in the simulation (0/1 vs 1/2). The 1/2 for the old syntax will make the intercept less interpretable compared to the 0/1 version. Secondly, the newer style syntax will allow you to add random error if you wish. 

The following will add additional random error to the outcome variable. This is not possible in the old syntax. 

```
# Explore data generation makes sense
simulate_fixed(data = NULL, sim_arguments) %>%
  simulate_error(sim_arguments) %>%
  generate_response(sim_arguments)

# Explore a single replication - model parameters
simulate_fixed(data = NULL, sim_arguments) %>%
  simulate_error(sim_arguments) %>%
  generate_response(sim_arguments) %>% 
  model_fit(sim_arguments) %>%
  extract_coefficients()

# replicate the simulation for power analysis
replicate_simulation(sim_arguments, 
                     simulate_fixed(data = NULL, sim_arguments) %>%
                       simulate_error(sim_arguments) %>%
                       generate_response(sim_arguments) %>% 
                       model_fit(sim_arguments) %>%
                       extract_coefficients()) %>%
  compute_statistics(sim_arguments)
```

If you have a minute, I'd appreciate if you can confirm these are indeed working on your end.
