### ISSUE TITLE
Question: Generate fixed effects in nested structure given the outcome

### ISSUE THREAD

**Issue by b1azk0** [lebebr01/simglm#60]
Hi, I've been redirected with my question to your package by the author of `powerlmm`. 

Is there any chance you could help me out with the following?

Is it possible to add `x1` and `x2` predictors to a dataset storing the outcome `y` with `subject` and `observation` variables defining nesting?

I'm looking for this, because when simulating data I wan't to control the amount of variance in `y` that is specific to  between and within two levels. So that running a NULL model of `lmer(y ~ 1 + (1 | subject))` shows that variances of random intercepts and residuals are for example 1 and 1 - 50/50 ratio (or any other of my choice). This part I know how to do using base R.

What I'm looking for, is a way to extend the null model dataset (leaving `y` as it was) with `x1` and `x2` predictors that can (but don't have to) be measured at different levels (subject level or observation level) but controlling for their correlations and overall effect on `y` - as in running an exemplary model of `lmer(y ~ x1 + x2 + (x1 | subject), data)'.

All the best,
blazej

**Comment by lebebr01** [comment]
Hi, thanks for the question. In general, this should be possible with simglm. I'm not sure I'm entirely following the entire situation you describe, however, below I've generated some code that may get you started. I'm happy to help modify if my understanding wasn't accurate.

### Null Model
```r 
library(simglm)
library(dplyr)

set.seed(321) 

sim_arguments <- list(
  formula = y ~ 1 + x1 + x2 +(1 | subject),
  reg_weights = c(0, 0, 0),
  fixed = list(x1 = list(var_type = 'continuous', mean = 0, sd = 1),
               x2 = list(var_type = 'continuous', mean = 0, sd = 1)),
  error = list(variance = 1),
  randomeffect = list(int_subject = list(variance = 1, var_level = 2)),
  sample_size = list(level1 = 10, level2 = 200)
)

nested_data <- sim_arguments %>%
  simulate_fixed(data = NULL, .) %>%
  simulate_randomeffect(sim_arguments) %>%
  simulate_error(sim_arguments) %>%
  generate_response(sim_arguments)

library(lme4)
summary(lmer(y ~ 1 + (1 | subject), data = nested_data))
```

The above includes `x1` and `x2` in the data generation, but they have no impact on the outcome (i.e. are uncorrelated with `y`). 

### x1 and x2 correlated with y

You can change their impact on the correlation with `y` by changing the values in `reg_weights` argument. For example:

```r 
library(simglm)
library(dplyr)

set.seed(321) 

sim_arguments <- list(
  formula = y ~ 1 + x1 + x2 +(1 | subject),
  reg_weights = c(0, .5, .4),
  fixed = list(x1 = list(var_type = 'continuous', mean = 0, sd = 1),
               x2 = list(var_type = 'continuous', mean = 0, sd = 1)),
  error = list(variance = 1),
  randomeffect = list(int_subject = list(variance = 1, var_level = 2)),
  sample_size = list(level1 = 10, level2 = 200)
)

nested_data <- sim_arguments %>%
  simulate_fixed(data = NULL, .) %>%
  simulate_randomeffect(sim_arguments) %>%
  simulate_error(sim_arguments) %>%
  generate_response(sim_arguments)

library(lme4)
summary(lmer(y ~ 1 + x1 + x2 + (1 | subject), data = nested_data))
```

### Additional Random Effects
Finally, you can also add additional random effects as you wish. For example, adding `x1` as a random effect would look like this:

```r
library(simglm)
library(dplyr)

set.seed(321) 

sim_arguments <- list(
  formula = y ~ 1 + x1 + x2 +(1 + x1 | subject),
  reg_weights = c(0, .5, .4),
  fixed = list(x1 = list(var_type = 'continuous', mean = 0, sd = 1),
               x2 = list(var_type = 'continuous', mean = 0, sd = 1)),
  error = list(variance = 1),
  randomeffect = list(int_subject = list(variance = 1, var_level = 2),
                                  x1_subject = list(variance = .5, var_level = 2)),
  sample_size = list(level1 = 10, level2 = 200)
)

nested_data <- sim_arguments %>%
  simulate_fixed(data = NULL, .) %>%
  simulate_randomeffect(sim_arguments) %>%
  simulate_error(sim_arguments) %>%
  generate_response(sim_arguments)

library(lme4)
summary(lmer(y ~ 1 + x1 + x2 + (1 + x1 | subject), data = nested_data))
```

The tidy_simulation and simulation_arguments vignettes can provide even more detail about things you can directly manipulate. 

Hope this is helpful and gets close to what you are looking for.

**Comment by b1azk0** [comment]
Hi, this is some great answer - it made my understanding of your package more clear. Thanks.

The three examples are very elegant by what I'm looking for is actually a mixture of them.

If we consider a dataset like the 3rd one:

```
library(simglm)
library(dplyr)

set.seed(321) 

sim_arguments <- list(
  formula = y ~ 1 + x1 + x2 +(1 + x1 | subject),
  reg_weights = c(0, .5, .4),
  fixed = list(x1 = list(var_type = 'continuous', mean = 0, sd = 1),
               x2 = list(var_type = 'continuous', mean = 0, sd = 1)),
  error = list(variance = 1),
  randomeffect = list(int_subject = list(variance = 1, var_level = 2),
                                  x1_subject = list(variance = .5, var_level = 2)),
  sample_size = list(level1 = 10, level2 = 200)
)

nested_data <- sim_arguments %>%
  simulate_fixed(data = NULL, .) %>%
  simulate_randomeffect(sim_arguments) %>%
  simulate_error(sim_arguments) %>%
  generate_response(sim_arguments)

library(lme4)
summary(lmer(y ~ 1 + x1 + x2 + (1 + x1 | subject), data = nested_data))
```

The call to lmer shows the following variance components:
```
Random effects:
  Groups   Name        Variance Std.Dev. Corr 
subject  (Intercept) 1.0533   1.0263        
x1          0.4850   0.6964   -0.08
Residual             0.9745   0.9872        
Number of obs: 2000, groups:  subject, 200
```

Now, while the above is the real model to analyse / describe, I would like to have control on what the variance components look like when I check the results of a unconditional model (on the same as before dataset): `summary(lmer(y ~ 1 + (1 | subject), data = nested_data))`  :
```

Random effects:
  Groups   Name        Variance Std.Dev.
subject  (Intercept) 1.143    1.069   
Residual             1.924    1.387   
Number of obs: 2000, groups:  subject, 200
```

Here, the residual variance of `y` is almost twice as big as the variance of `y` at `subject intercept` level.

The ratio of those two variances is something that I'd like to define when generating `nested_data` for the random slope and intercept model `lmer(y ~ 1 + x1 + x2 + (1 + x1 | subject))`.

Let me know if this explains anything :) 
I'm starting to think that there is virtually now way to do what I want, but truth is i'm no expert here.

**Comment by b1azk0** [comment]
That would not do the trick. What I'm after is testing different full models (with various covariates) but given a specific variance structure on the unconditional model that is solely within `y`  nested in subjects.
If I can fix the ratio of those variances at the unconditional level, and then add covariates based upon present data, I'm almost at home.

What I was actually thinking, was setting up data for the NULL model with predefined ratios, and than adding predictors at different levels - for example as in solving for `x = (-b / a) + (y / a))` if we know `y = b + a*x`.
I've tried but it was pure guesswork and I definitely wouldn't know how to extend this to multiple covariates on different levels of measurement and their impact on `y`.

**Comment by b1azk0** [comment]
Here is an example (by trial and error) that gives me almost what I want:

```
set.seed(321) 

sim_arguments <- list(
  formula = y ~ 1 + x1 + x2 + (1 + x1 | subject),
  reg_weights = c(0, .5, .4),
  fixed = list(x1 = list(var_type = 'continuous', mean = 0, sd = 1, var_level = 2),
               x2 = list(var_type = 'continuous', mean = 0, sd = 1, var_level = 2)),
#  error = list(variance = 1),
  randomeffect = list(int_subject = list(variance = .25, var_level = 2),
                      x1_subject = list(variance = .5, var_level = 2)),
  sample_size = list(level1 = 7, level2 = 50)
)

nested_data <- sim_arguments %>%
  simulate_fixed(data = NULL, .) %>%
  simulate_randomeffect(sim_arguments) %>%
  simulate_error(sim_arguments) %>%
  generate_response(sim_arguments)


library(lme4)
summary(lmer(y ~ 1 + x1 + x2 + (1 + x1 | subject), data = nested_data))
summary(lmer(y ~ 1 + (1 | subject), data = nested_data)
```
Summary of the full model shows `x1` and `x2` are significant, the slope of `x1` is also valid.
**And** when you look at the 2nd (NULL) model, residual variance is 1.09 and the subject variance is 0.97. So I can tell that the ratio is almost 50/50 <- and that's precisely what I'm trying to control

**Comment by b1azk0** [comment]
I guess the real question now is, can I somehow control this ratio and avoid guesswork as I did above?
I don't feel strong enough in math / linear algebra to sort this out by my own

**Comment by b1azk0** [comment]
Here is an other example (achieved by trial and error):
consider a data set like this: https://pastebin.com/FHwVgqXA (note there is no random slope in this example)
When running a model of `lmer(y ~ a + b + (1|Subject), data)` I see that both `a` and `b` are significant.
When running a call `m0<-lmer(y ~ 1 + (1|Subject), data)` I can tell that residual variance to sigma variance is almost 1 to 1

```
> var.fraction(m0)
lmer(formula = y ~ 1 + (1 | Subject), data = dd)
[1] "The residual variance of y is: 1.457"
[1] "The random variance of null model is: 1.53"
[1] "Theta is: 1.02"
[1] "Fraction of rand to resid variance is :  21/20"
[1] "Fraction of resid to rand variance is :  19/20"
```
(this is the output of a custom function I wrote myself to speed up checking what Im interested in)

**Comment by lebebr01** [comment]
What you are looking for is the ICC (intraclass correlation) which defines the percentage of variation at level 2 in this case [wikipedia article](https://en.wikipedia.org/wiki/Intraclass_correlation#Modern_ICC_definitions:_simpler_formula_but_positive_bias).

Where these differ for your case is that these are generally calculated from what I call the unconditional model (i.e. one with no predictors). Then it is easy to control the ratio of variances based on the ICC in a formulaic standpoint. When you bring in predictors, which reduce the variance estimates for the random effects at the level the variables are predicting, controlling the ICC is more complicated as the additional variables will add variability when not being modeled. 

I personally have never done simulation in this way, therefore I likely won't be too much help in figuring a formulaic way of manipulating these variances with additional variables included.

**Comment by b1azk0** [comment]
Thank for your answer and clarification. 

Before I open a new question: is a there a quick way to generate repeated measures design with only categorical predictors (e.g. 2x2x2 within subject) where the significance of interaction effects could be controlled? My gut says that it should be doable but I have no clue from where to start.

Thank you once again
