### ISSUE TITLE
Specify mean and SD of response

### ISSUE THREAD

**Issue by DominiqueMakowski** [lebebr01/simglm#62]
Dear @lebebr01,

I plan on doing a simulation study based on the simulation of different models types (linear and logistic), sample sizes, noise (error), and effect size, and your package seems absolutely perfect for it. 

However, for linear regressions, I would like the specified regression parameters to be "standardized", i.e., related to a standardized outcome response (mean = 0 and SD = 1). While I found a way of creating standardized predictors (using `fixed = list(x = list(var_type = 'continuous', mean = 0, sd = 1))` in sim_args), I haven't found a way of doing that for the response variable.

Is this possible? Or is there maybe another way of simulating linear regression data based on standardized coefs? Thanks a lot!

**Comment by lebebr01** [comment]
Hi @DominiqueMakowski, 

Thanks for your interest in the package. One way to get standardized coefficients would be to specify the error variance to be fixed to one. This can be done using, `error = list(variance = 1)` inside of the simulation arguments. This may seem counter intuitive, but this should be the variance of response variable after conditioning out the effect of the predictors. 

You could also convert manually, (this may be a good simple function for me to add in the future), to convert between standardized and unstandardized coefficients. This may be particularly useful if you would like to vary the error variance (Sy below). 

B = b * ( Sx / Sy)

Feel free to ping me with any other thoughts/questions/problems. Best.

**Comment by DominiqueMakowski** [comment]
Thanks a lot for your answer. Indeed, I would like to additionally vary the error variance. 

I am in a kinda complicated scenario where I would need to generate data based on standardized coefficients with a varying amount of noise, and I would like the avoid having to retrieve the standardized coefficients a posteriori (as these might not have a rather unclear correspondence with the coefficient I have specified (and the one that I would need the generative process to be based on)).

To give you a more general view, here's the code I have so far:

```r
# convenience function
generate_data <- function(effect_size=0, outcome_type="linear", error=0.01){
  
  if (outcome_type == "linear"){
    outcome_type = NULL
    reg_weights = c(0, effect_size)
    } else{
      outcome_type = "binary"
      reg_weights = c(0.5, sqrt(3)/pi*effect_size)  # Based on Cohen's (1988) log-odds -> standardized d transformation
  }
  
  # Sim arguments
  sim_arguments <- list(
    formula = y ~ x,
    fixed = list(x = list(var_type = 'continuous', mean = 0, sd = 1)),
    error = list(variance=error),
    sample_size = 50,
    reg_weights = reg_weights,
    outcome_type = outcome_type
  )
  
  # Generate data
  data <- simglm::simulate_fixed(data = NULL, sim_arguments) %>% 
    simglm::simulate_error(sim_arguments) %>%
    simglm::generate_response(sim_arguments)
  
  return(data)
}

# ------------------------------------------------------------------------------
# Parameters
effect_sizes <- c(0, 0.1, 0.2, 0.5, 0.8)
outcome_types <- c("linear", "binary")
error_amount <- c(0.01, 0.1, 0.5, 1)

# Start loop
for(effect_size in effect_sizes){
  for(outcome_type in outcome_types){
    for(error in error_amount){
      cat(".")
      # Get data
      data <- generate_data(effect_size, outcome_type, error)
      
      # Compute model
      if(outcome_type == "linear"){
        model <- lm(y ~ x, data=data)
      } else{
        model <- glm(y ~ x, data=data, family="binomial")
      }
    }
  }
}
```
As you can see, I am trying to orthogonally obtain logistic and linear models with a specified initial standardized coefficient (and a varying level of noise). 

I would like to further see the influence of a prior specified correcty (i.e., located at the specified initial standardized coefficient) on the actual parameters depending on the noise level etc. for Bayesian regressions. Hence the need of pre-specifiying the standardized coefs rather than retrieving it post-hoc from the observed coefficient (as then I can't delineate the effect of noise from other processes).

I hope it is clear...

**Comment by lebebr01** [comment]
Hi @DominiqueMakowski,

This is the type of function that I am going to think about adding to the R package for conversion internally. This should work for the linear regression portion, but I'd have to think a bit more to generalize it to work for the logistic case.

```r
convert_beta <- function(beta = NULL, effect_size = NULL, error_y, error_x) {
  
  if(is.null(beta)) {
    effect <- effect_size * (error_y / error_x)
  }
  
  if(is.null(effect_size)) {
    effect <- beta * (error_x / error_y)
  }
  effect
}
```

You could then run the conversion of standardized to unstandardized as a function of effect size and y error variance. This shows that these are reciprocals of one another. After conversion, you could pass the unstandardized version to the simglm package as reg_weights. 

```r
convert_beta(effect_size = .8, error_y = .01, error_x = 1)
convert_beta(beta = .008, error_y = .01, error_x = 1)
```

**Comment by DominiqueMakowski** [comment]
Thanks a lot.

Let's say I want some standardized data with a (standardized) regression coef of 0.2 and an error variance (by the way, does it correspond to SD or is it actual variance?) of 0.1.

Based on your suggestions and from what I understand, this code should generate standardized data which regression coefficient is equal to the desired specification.
```r
convert_beta <- function(beta = NULL, effect_size = NULL, error_y, error_x) {
  
  if(is.null(beta)) {
    effect <- effect_size * (error_y / error_x)
  }
  
  if(is.null(effect_size)) {
    effect <- beta * (error_x / error_y)
  }
  effect
}


desired_std_coef <- 0.2
error <- 0.1
actual_coef <- convert_beta(effect_size = desired_std_coef, error_y = error, error_x = 1)

# Sim arguments
sim_arguments <- list(
  formula = y ~ x,
  fixed = list(x = list(var_type = 'continuous', mean = 0, sd = 1)),
  error = list(variance=1),
  sample_size = 50,
  reg_weights = c(0, actual_coef)
)
  
# Generate data
data <- simglm::simulate_fixed(data = NULL, sim_arguments) %>% 
  simglm::simulate_error(sim_arguments) %>%
  simglm::generate_response(sim_arguments)

# Standardize data
data <- as.data.frame(scale(data))

# Fit and check model
model <- lm(y ~ x, data=data)
summary(model)
```

However, it does not seem to be the case. I am not sure where am I wrong 😕 

(If I run a loop with different specified coefs and compare it to the end coefs from the regression with different errors, I obtain the following graph)

![image](https://user-images.githubusercontent.com/8875533/55846935-14866300-5b7a-11e9-9402-306ef706c8a1.png)


Sorry to bother with this, I appreciate your help :)

**Comment by lebebr01** [comment]
There are a few things happening here, I think (may be wrong as I've never directly done this in this way before, so I'm learning as well). First, I believe you will want the variance passed to error inside `sim_arguments`, to match with the error variance specified. So if you are using 0.1, then this variance should be passed to the error in the `sim_arguments` portion. Secondly, you shouldn't need to standardize the data prior to modeling it.

Once these are changed, on my end I'm able to recreate the `actual_coef` object that you specified with the code below (note, I upped the sample size a lot for this testing, the small sample size in your simulation will increase noise). 

```r
convert_beta <- function(beta = NULL, effect_size = NULL, error_y, error_x) {
  
  if(is.null(beta)) {
    effect <- effect_size * (error_y / error_x)
  }
  
  if(is.null(effect_size)) {
    effect <- beta * (error_x / error_y)
  }
  effect
}


desired_std_coef <- 0.2
error <- .2
actual_coef <- convert_beta(effect_size = desired_std_coef, error_y = sqrt(error), error_x = 1)

# Sim arguments
sim_arguments <- list(
  formula = y ~ x,
  fixed = list(x = list(var_type = 'continuous', mean = 0, sd = 1)),
  error = list(variance = error),
  sample_size = 100000,
  reg_weights = c(0, actual_coef),
  replications = 100
)

# Generate data
data <- simglm::simulate_fixed(data = NULL, sim_arguments) %>% 
  simglm::simulate_error(sim_arguments) %>%
  simglm::generate_response(sim_arguments) 

# Standardize data
# data <- as.data.frame(scale(data))

# Fit and check model
model <- lm(y ~ x, data=data)
coef(model)
```

Then you can take the coef object and pass this back to the `convert_beta` function to convert it back to the standardized metric. Essentially, the logic follows as such, once you convert to the unstandardized metric, these are the values the model should recreate, in order to ensure you are recreating the standardized coefficients, you need to transform them back to that metric.

```r
computed_std_coef <- convert_beta(beta = coef(model)[2], error_y = sqrt(error), error_x = 1)

all.equal(computed_std_coef,
                desired_std_coef, 
check.attributes = FALSE)
```

The other thing to note based on your question, the `convert_beta` function requires SDs, but the variance needs to be passed to the error portion of `sim_arguments`. In all of the code above, I assumed the error object was the variance (note the `sqrt()` call in the `convert_beta` function.

**Comment by DominiqueMakowski** [comment]
Thanks a lot!
