### ISSUE TITLE
DOCS: End users only need to load the future package - not future.apply

### ISSUE THREAD

**Issue by HenrikBengtsson** [lebebr01/simglm#66]
Nothing important, but I think that the end user of your package does not really need to attach future.apply as in:

https://github.com/lebebr01/simglm/blob/f7bf0e1677cc3403db3d39f24ec6e923b01a48e3/vignettes/tidy_simulation.Rmd#L302-L308

https://github.com/lebebr01/simglm/blob/7412056f0b89eed9633ff504d3d5f364df2b068e/vignettes/simulation_arguments.Rmd#L610-L617

It should be enough for them to be aware of the future package and only attach that one, as in:
```r
library(future)
plan(multicore)
```
because you already import from future.apply internally.

Users could even avoid attaching the future package and just load it by using:
```r
future::plan(future::multicore)
```
The latter is a bit noisy so I personally tend to avoid that one in examples.

**Comment by lebebr01** [comment]
This makes sense, thanks for the suggestion/clarification.
