### ISSUE TITLE
What is the reg_weights_model parameter?

### ISSUE THREAD

**Issue by bwiernik** [lebebr01/simglm#78]
In the tidy simulation vignette, several examples include a `reg_weights_model` argument. It's not clear to me what this argument is? I see that `reg_weights` is the weights for the data generating process, but doesn't `model_fit` just estimate weights based on the simulated sample? What does the `reg_weights_model` argument do?

**Comment by lebebr01** [comment]
The `reg_weights_model` argument allows for user specification of the regression coefficients to be compared to the empirical model fitted values. This allows users to specify these outside of those use for the data generation process. If this argument isn't specified, the simulation based regression coefficients are used, this is the default behavior and most common use case.
