### ISSUE TITLE
Table joining duplicates crit_value column

### ISSUE THREAD

**Issue by bwiernik** [lebebr01/simglm#80]
Following up on #79, the current joining approach specifies only `by = "term"`. This has the effect that when `power_computation` and `type_1_error_computation` are joined, they produce duplicate `crit_value` columns which are renamed `crit_value.x` (from power_computation) and `crit_value.y` (from type_1_error_computation).

This could be fixed by dropping the `by` argument and simply having the rows be matched on all columns or, alternatively, by renaming `crit_value` in both tables to give them unique names that will remain more informative than `crit_value.x` and `crit_value.y`.

**Comment by lebebr01** [comment]
Just an fyi here, I chose to rename the columns. This will allow the flexibility in the future to allow different values for power/t1e, unsure if this would be useful offhand, but it could be possible to keep them with different names.
