### ISSUE TITLE
Model fit functions fail with factors with more than two levels

### ISSUE THREAD

**Issue by phasedchirp** [lebebr01/simglm#85]
The data simulation functions work when give a factor with three or more levels but if I try to use the `model_fit` functions, they fail with the error `Error in eval(predvars, data, env) : object '<variable name> not found`. Reproducible example included below:

```r
# doesn't work

sim_args <- list(
  formula = y ~ 1 + group + z,
  fixed = list(
    group = list(
      var_type = 'factor',
      levels = c('b','a', 'o')
    ),
    z = list(var_type = 'continuous',dist = runif, min = 0, max = 10)
  ),
  sample_size = 100,
  error = list(variance = 2),
  reg_weights = c(0, 0.15, 0.01, .1)
)



simulate_fixed(data = NULL, sim_args) %>%
  simulate_error(sim_args) %>%
  generate_response(sim_args) %>%
  model_fit(sim_args)


# works

sim_args <- list(
  formula = y ~ 1 + group + z,
  fixed = list(
    group = list(
      var_type = 'factor',
      levels = c('b','a')
    ),
    z = list(var_type = 'continuous',dist = runif, min = 0, max = 10)
  ),
  sample_size = 100,
  error = list(variance = 2),
  reg_weights = c(0, 0.15, .1)
)


simulate_fixed(data = NULL, sim_args) %>%
  simulate_error(sim_args) %>%
  generate_response(sim_args) %>%
  model_fit(sim_args)
```

Additional details:
* Using development version installed from github but this happened with the CRAN version too
* reproduced on Windows and Ubuntu with R 3.6.3 and 4.1.0

**Comment by lebebr01** [comment]
Thanks for sending this @phasedchirp . I've posted a fix that I hope makes the naming conventions for the simulation mechanics more robust. Needs further testing, but your code runs on my end from the most recent version on GH.
