### ISSUE TITLE
problem replicate_simulation with multilevel models on Mac

### ISSUE THREAD

**Issue by mkissine** [lebebr01/simglm#90]
When trying to simulate a glmer model with a random intercept (`model_function = 'glmer', family=binomial(link='logit')`), the `replicate_simulation` yields the error:
```
Error in glmer(formula = y ~ 1 + x + (1 | participant), family = list( : 
  impossible to find the function "glmer"
```

I thought that something was wrong with my code, but then I tried the example on pp. 26-27 of LeBeau. (2019). Power Analysis by Simulation using R and simglm. In Iowa Research Online. University of Iowa. https://doi.org/10.17077/f7kk-6w7f and I get the same error.
```
Erreur dans lmer(formula = y ~ 1 + time + sex + time:sex + (1 + time | individual),  : 
  impossible de trouver la fonction "lmer"
```

This problem subsists with the dev version of the package. I'm on macOS Monterey with the last R and RStudio versions.

**Comment by lebebr01** [comment]
Thanks for the interest in the package. I can't verify the first piece, but the second code runs for me on the latest OSX. 

This error is likely occurring due to not having the lme4 package loaded (ie., `library(lme4)`), the simglm package does not automatically load this package to reduce the number of dependencies. 

Hope this helps.

**Comment by mkissine** [comment]
No, unfortunately, this doesn't seem to be the issue; lme4 is loaded. And I tried on two different computers (both Mac, though).

**Comment by mkissine** [comment]
I forgot to mention that this issue doesn't arise when simulating non-nested models (e.g. with model_function = 'lm')

**Comment by lebebr01** [comment]
Unfortunately, I'm not able to provide additional support without reproducible code as the code from the paper you reference works on my end using the current version from GH.

**Comment by mkissine** [comment]
Here is my code:

set.seed(321)
plan(multiprocess)
sim_arguments<-list(
  formula=y~1+phase+(1|participant),
  reg_weights=c(-2.818200, -8.688903),
  fixed=list(phase= list(var_type = 'factor', levels = c(0, 1), prob=c(0.3,0.7), var_level=1)),
  randomeffect = list(participant = list(variance = 9.874, var_level = 2)),
 sample_size=list(level1=5, level2=103),
  outcome_type = 'binary',
 replications = 2,
 model_fit = list(formula = y~1+phase+(1|participant),
                   model_function = 'glmer', family=binomial(link='logit')),
  extract_coefficients = TRUE
  )
replicate_sim <- replicate_simulation(sim_arguments)






Le 14 avr. 2022 à 22:08, Brandon LeBeau ***@***.******@***.***>> a écrit :



Unfortunately, I'm not able to provide additional support without reproducible code as the code from the paper you reference works on my end using the current version from GH.

**Comment by lebebr01** [comment]
The following works on my end. I do not directly have another computer to test on. Note, I did receive a similar error when the `plan(multiprocess)` was in there, perhaps due to this process being deprecated or some other issue with the future package. 

```r
library(simglm)
library(lme4)

set.seed(321)
sim_arguments<-list(
  formula=y~1+phase+(1|participant),
  reg_weights=c(-2.818200, -8.688903),
  fixed=list(phase= list(var_type = 'factor', levels = c(0, 1), prob=c(0.3,0.7), var_level=1)),
  randomeffect = list(participant = list(variance = 9.874, var_level = 2)),
  sample_size=list(level1=5, level2=103),
  outcome_type = 'binary',
  replications = 2,
  model_fit = list(formula = y~1+phase+(1|participant),
                   model_function = 'glmer', family=binomial(link='logit')),
  extract_coefficients = TRUE
)
replicate_sim <- replicate_simulation(sim_arguments)
```

**Comment by mkissine** [comment]
It is a glitch with the future package. Thank you so much! And thanks for this superb package.
Mikhail Kissine
----------------------------------------
Université Libre de Bruxelles
CP 175
50 avenue F.D. Roosevelt
1050 Bruxelles
Belgium

+32 2 650 66 64
https://mikhail.kissine.web.ulb.be

Professeur de Recherche Francqui 2019-2022

ACTE (Autisme en Contexte - Théorie & Expérience) : acte.ulb.be<http://acte.ulb.be>
Centre de recherche en linguistique LaDisco : ladisco.ulb.ac.be<http://ladisco.ulb.ac.be>
ULB Neuroscience Institute : uni.ulb.ac.be<http://uni.ulb.ac.be>


Le 14 avr. 2022 à 22:29, Brandon LeBeau ***@***.******@***.***>> a écrit :



The following works on my end. I do not directly have another computer to test on. Note, I did receive a similar error when the plan(multiprocess) was in there, perhaps due to this process being deprecated or some other issue with the future package.

library(simglm)
library(lme4)

set.seed(321)
sim_arguments<-list(
  formula=y~1+phase+(1|participant),
  reg_weights=c(-2.818200, -8.688903),
  fixed=list(phase= list(var_type = 'factor', levels = c(0, 1), prob=c(0.3,0.7), var_level=1)),
  randomeffect = list(participant = list(variance = 9.874, var_level = 2)),
  sample_size=list(level1=5, level2=103),
  outcome_type = 'binary',
  replications = 2,
  model_fit = list(formula = y~1+phase+(1|participant),
                   model_function = 'glmer', family=binomial(link='logit')),
  extract_coefficients = TRUE
)
replicate_sim <- replicate_simulation(sim_arguments)
